### ISSUE TITLE
Improve documentation 

### ISSUE THREAD

**Issue by AngelBlock** [HeroesHQ/HEROES#107]
The mobile screens look bad in the docs, together with wide text, we need to use desktop screens

- [ ] replace mobile screens with desktop
- [ ] use dark scheme if possible.

**Comment by starpause** [comment]
Re: color scheme, I've enabled the toggle so everyone can change it to their preference.

Re: Mobile/Desktop screens, I also think this is up to preference. For the next walkthrough I'll try desktop. The reason I like mobile screenshots is because you can see more in a smaller picture, embedded desktop images always feel zoomed out.
