### ISSUE TITLE
[WORK REQUEST] Simply on-chain logic of deadlines 

### ISSUE THREAD

**Issue by Kisgus** [HeroesHQ/HEROES#157]
🤼‍♂️  **What problem is your work solving.**

We have had issues with on-chain deadline,  both of funder and hunter side, it's too complex and not intuitive and leads to funds stay in escrow longer than expected

🎉  **Describe the work you'd like**

Idea for simplifying it:

 - [x] Rule 1: (On-chain deadline) Bounty funder will always have to specify a deadline when creating a bounty

- [ ] Rule 2:(On-chain deadline) Bounty hunter will always match the deadline set forth by the Funder, hence the hunter will not need to select any deadline

- [ ]  Rule 3: (Off-chain) In case hunter wanna give an estimate on when work is done (as basis of why they should get selected to work on a bounty, this happens off-chain.

## 🔗   Open questions

If we assume this solution is in place, what other ways of having funds sitting in Escrow can we think of?

**Comment by AngelBlock** [comment]
### Team considerations are below:


#### Practically all the changes described in the task are already supported by the contract. We can remove from the UI the usage options that do not fit into the extended scheme.

The changes that need to be made are:
1. **UI**: When creating a bounty, remove the "Specify deadline" option. A deadline must always be explicitly stated (the contract will not use the WithoutDeadline value), and remove the "Allow the hunter to specify their own deadline" option. The value allowing the freelancer not to specify their own deadline will always be used.
2. **UI, smart-contract, backend**: When creating a bounty, an optional information field, Time Commitment (amount of time units - hours, days, etc.), can be added. This is a desirable timeframe for the bounty owner, indicating the approximate time for task completion. This field will give freelancers the opportunity to compare their capabilities with the client's expectations before offering their services. It will not affect the contract's operation.
3. **UI, backend**: When a freelancer creates a claim, do not use the deadline field at the smart-contract level. Thus, for the smart-contract, the freelancer must complete the work no later than the deadline specified by the bounty owner at its creation. In the claim creation form, leave an optional deadline field, which will be used only for informational purposes outside of the blockchain.
4. **UI, backend**: Since there is still a deadline for the freelancer, which the bounty owner has specified, it is necessary to improve the notification of the performer about the current state of their claim. For example: if the freelancer exceeds the deadline, then a message about this should be issued (currently, the countdown timer just stops), send messages by email, before performing an action that will irreversibly change the status of the claim (canceled, overdue) - issue a warning about the irreversibility, suggest an alternative option - add a button to send a message to the owner with a request to extend the bounty deadline.

Also, please note that the proposed changes do not take into account other possible use cases that may be in demand. 

The deadline specified by the bounty owner, in the form of an end date, may be inconvenient in the case when a "One For All" bounty with a large number of slots is created, intended for use over a long period of time. In such a case, all freelancers, who at different times take just one slot, will have the opportunity to perform it throughout the common term for all slots.

For this case, the contract supports (but is not used in the current version of the UI) the possibility of specifying a deadline in the form of a time period (rather than a specific overall date), which will determine the individual deadline for the freelancer from the moment they start working on a separate bounty slot.

Also, for this type of deadline, the possibility of extending the execution period for an individual slot, if necessary, by the bounty owner, without changing the overall deadline for all other slots, can be developed.

**Comment by AngelBlock** [comment]
Please also add:

- [ ]  the option to configure the HEROES-wide parameter (configurable by admins) of maximum deadline which can be specified by founder and set it up to 3 month default.
